name = "corporate-website"
compatibility_date = "2024-03-23"

[site]
bucket = ".next/static"
include = ["public/**/*"]

[build]
command = "yarn build"
cwd = "."

[build.upload]
format = "service-worker"

# Add Pages-specific configuration
pages_build_output_dir = ".next"

# Add Next.js specific configuration
[build.environment]
NODE_VERSION = "18" 